language: node_js
node_js:
  - '0.12.7'
install:
  - npm install --production
  - export PHANTOMJS_BIN=$TRAVIS_BUILD_DIR/node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs
  - phantomjs --version
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/node_modules"
notifications:
  email: false
